# Generated by Django 3.0.8 on 2020-07-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5)),
                ('positive_cases', models.BigIntegerField()),
                ('tested', models.BigIntegerField()),
                ('percent_positive', models.DecimalField(decimal_places=3, max_digits=3)),
                ('updated_date', models.DateTimeField()),
                ('representative', models.CharField(max_length=50)),
            ],
        ),
    ]
