# Generated by Django 3.0.8 on 2020-07-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Councilor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='town',
            old_name='representative',
            new_name='coucilor',
        ),
    ]
