# Generated by Django 3.0.8 on 2020-07-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20200713_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='town',
            old_name='coucilor',
            new_name='councilor',
        ),
    ]
