# Generated by Django 3.0.8 on 2020-10-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20200713_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='updated_date',
        ),
    ]
