# Generated by Django 3.0.8 on 2020-10-22 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_remove_town_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='councilor',
        ),
    ]
