# Generated by Django 3.0.8 on 2020-10-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_remove_town_councilor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='percent_positive',
            field=models.CharField(max_length=10),
        ),
    ]
